import type { PlayerSeasonStat } from "@/lib/types";

export const STAT_DESCRIPTIONS: Partial<Record<keyof PlayerSeasonStat, string>> = {
  scoring_avg:
    "Average strokes taken per round, adjusted for course difficulty. Like golf itself, lower is better — think of it as the opposite of a batting average.",
  birdie_avg: "Average number of birdies (one shot under par) made per round.",
  total_birdies: "Total birdies made across the whole season.",
  total_eagles:
    "Total eagles (two shots under par on a single hole) made across the season — a rare, exciting feat.",
  birdie_or_better_pct: "The percentage of holes played where the player made a birdie or better.",
  bogey_avoidance_pct:
    "The percentage of holes played where the player made a bogey (one shot over par) or worse. Lower is better — it rewards avoiding big mistakes.",
  driving_distance: "Average tee-shot distance on par-4s and par-5s, in yards.",
  driving_accuracy_pct:
    "Percentage of tee shots that land in the fairway, instead of the rough, trees, or a hazard.",
  gir_pct:
    "Greens in Regulation — the percentage of holes where the green is reached in the 'expected' number of shots (2 shots on a par 4, etc.), leaving just a putt for par or better.",
  scrambling_pct:
    "When a player misses the green, this is how often they still make par or better anyway. It measures short-game recovery skill.",
  sand_save_pct:
    "Of the times a ball lands in a bunker near the green, the percentage where the player still makes par or better.",
  putting_avg: "Average putts taken per hole where the green was reached in regulation. Lower is better.",
  putts_per_round: "Average total putts taken across a full 18-hole round, however the player got to the green.",
  sg_total:
    "Strokes Gained: Total — the single best measure of overall play. It compares a player's score to the field average that round and expresses the gap in strokes. +2.0 means they played 2 strokes better than an average field.",
  sg_tee_to_green:
    "Strokes gained on everything except putting — tee shots, approach shots, and shots around the green, combined.",
  sg_off_the_tee: "Strokes gained specifically off the tee on par-4s and par-5s — a mix of distance and accuracy.",
  sg_approach: "Strokes gained on approach shots hit toward the green from the fairway or rough.",
  sg_around_green:
    "Strokes gained on short-game shots within roughly 30 yards of the green (chips, pitches, etc.), not counting putts.",
  sg_putting: "Strokes gained on the putting green alone.",
  top_10: "Number of tournaments the player finished in the top 10.",
  finish_1st: "Number of tournaments the player finished in 1st place (a subset of Top 10 Finishes).",
  finish_2nd: "Number of tournaments the player finished in 2nd place (a subset of Top 10 Finishes).",
  finish_3rd: "Number of tournaments the player finished in 3rd place (a subset of Top 10 Finishes).",
  wins: "Number of tournaments the player won outright that season.",
  official_money: "Total prize money earned from official PGA Tour events that season.",
  fedexcup_rank:
    "Position in the FedExCup standings — a season-long points race, like a championship leaderboard, that determines who reaches the Tour's postseason and its bonus pool.",
  fedexcup_points: "Points earned toward the season-long FedExCup standings — bigger events and better finishes earn more.",
  fedexcup_wins: "Wins counted toward the FedExCup season, which can differ slightly from total Tour wins.",
  fedexcup_top10s: "Top-10 finishes counted toward the FedExCup season.",
  world_rank:
    "Official World Golf Ranking — a player's rank among ALL professional golfers worldwide (not just the PGA Tour), based on performance over a rolling two-year window.",
  world_rank_avg_points: "The average points-per-event used to calculate a player's Official World Golf Ranking.",
  all_around_rank:
    "A combined ranking across many statistical categories at once, rewarding players who are strong all-around rather than elite in just one area.",
  all_around_total: "The composite score behind the All-Around Ranking — lower reflects a stronger all-around season.",
};

// Descriptions for the 72 curated categories pulled from PGA Tour's own
// stats API beyond the original 25 core stats (see
// scripts/fetch_extended_stats.py for the statId each key maps to).
export const EXTENDED_STAT_DESCRIPTIONS: Record<string, string> = {
  par3_scoring_avg: "Average score on par-3 holes only — a read on iron and wedge precision on the shorter holes.",
  par4_scoring_avg: "Average score on par-4 holes only, the most common hole type on Tour.",
  par5_scoring_avg: "Average score on par-5 holes only. Long hitters who can reach the green in two shots tend to score well here.",
  scoring_avg_actual: "The player's raw scoring average with no adjustment for course difficulty — the literal average strokes per round.",
  scoring_avg_before_cut: "Scoring average using only rounds played before the cut (the 36-hole cutoff that eliminates players from the weekend) — a read on early-tournament form.",
  final_round_scoring_avg: "Average score specifically in the final round of tournaments — how a player performs with the trophy on the line.",
  bounce_back: "The percentage of times a player makes a bogey (or worse) and then bounces back with a birdie or better on the very next hole.",
  consecutive_cuts: "The player's current streak of made cuts (tournaments where they played all four rounds) in a row.",
  rounds_in_60s: "Number of rounds shot in the 60s (under 70 strokes) — a marker of consistently low scoring.",
  sub_par_rounds: "Number of rounds finished under par for the course.",
  lowest_round: "The single lowest (best) round score shot all season.",
  bogey_average: "Average number of bogeys made per round.",
  birdie_to_bogey_ratio: "How many birdies a player makes for every bogey. Above 1.0 means more birdies than bogeys — a sign of aggressive, well-rounded play.",
  total_driving: "A combined ranking of driving distance and driving accuracy (the two ranks added together) — rewards players who are long AND straight, not just one or the other.",
  longest_drives: "The single longest drive the player hit all season, in yards.",
  driving_pct_300_plus: "The percentage of tee shots that traveled 300 yards or more.",
  left_tendency: "Of a player's missed fairways, the percentage that missed to the left.",
  right_tendency: "Of a player's missed fairways, the percentage that missed to the right.",
  approach_50_75: "Average proximity to the hole on approach shots from 50-75 yards out.",
  approach_75_100: "Average proximity to the hole on approach shots from 75-100 yards out.",
  approach_100_125: "Average proximity to the hole on approach shots from 100-125 yards out.",
  approach_125_150: "Average proximity to the hole on approach shots from 125-150 yards out.",
  approach_150_175: "Average proximity to the hole on approach shots from 150-175 yards out.",
  approach_175_200: "Average proximity to the hole on approach shots from 175-200 yards out.",
  approach_200_plus: "Average proximity to the hole on approach shots from more than 200 yards out.",
  proximity_to_hole: "Average distance the ball finishes from the hole on approach shots, across all distances and lies — the single best measure of iron and wedge accuracy.",
  proximity_arg: "Average distance the ball finishes from the hole on short-game shots around the green (chips and pitches).",
  proximity_rough: "Average proximity to the hole on approach shots hit from the rough.",
  proximity_sand: "Average proximity to the hole on approach shots hit from a fairway bunker.",
  proximity_fringe: "Average proximity to the hole on shots played from the fringe, the short grass just off the green.",
  going_for_the_green: "On reachable par 5s, the percentage of times a player attempts to reach the green in two shots instead of laying up.",
  going_for_green_birdie_or_better: "Of the times a player goes for the green in two on a par 5, the percentage that results in a birdie or better.",
  scrambling_rough: "When missing the green into the rough, the percentage of time the player still makes par or better.",
  scrambling_sand: "When missing the green into a bunker, the percentage of time the player still makes par or better.",
  scrambling_fringe: "When just off the green on the fringe, the percentage of time the player still makes par or better.",
  scrambling_other: "Scrambling percentage (making par or better after missing the green) from locations other than rough, sand, or fringe.",
  one_putt_pct: "The percentage of holes where the player needed only one putt.",
  three_putt_avoidance: "The percentage of holes where a player took three or more putts. Lower is better — it measures avoiding putting disasters.",
  putting_from_3ft: "The percentage of putts made from 3 feet.",
  putting_from_5ft: "The percentage of putts made from 5 feet.",
  putting_inside_5ft: "The percentage of putts made from inside 5 feet — the short, all-but-automatic putts.",
  putting_from_10ft: "The percentage of putts made from 10 feet.",
  putting_from_25plus: "The percentage of putts made from beyond 25 feet — mostly long-range putts where a make is a bonus.",
  putts_made_over_10ft_per_event: "Average number of putts made from beyond 10 feet per tournament played.",
  putts_made_over_20ft_per_event: "Average number of putts made from beyond 20 feet per tournament played.",
  power_rating: "PGA Tour's composite index combining driving distance and other power-related stats into a single score.",
  accuracy_rating: "PGA Tour's composite index combining driving accuracy and related stats into a single score.",
  short_game_rating: "PGA Tour's composite index combining scrambling and other short-game stats into a single score.",
  putting_rating: "PGA Tour's composite index combining putting stats into a single score.",
  ball_striking: "A composite score combining Greens in Regulation and Total Driving ranks — an all-in-one measure of long-club ball-striking.",
  scoring_rating: "PGA Tour's composite index combining scoring-related stats into a single overall score.",
  ryder_cup_points: "Points earned toward qualifying for the U.S. Ryder Cup team, the biennial team event against Europe.",
  presidents_cup_points_us: "Points earned toward qualifying for the U.S. Presidents Cup team, the biennial team event against an International squad.",
  presidents_cup_points_intl: "Points earned toward qualifying for the International Presidents Cup team (for players outside the U.S. and Europe).",
  consecutive_birdies_streak: "The most consecutive holes in a row a player made a birdie or better during the season.",
  best_60s_streak: "The longest streak of consecutive rounds shot in the 60s during the season.",
  current_par_or_better_streak: "The player's active streak of rounds finished at par or better.",
  last15_scoring: "A rolling snapshot of scoring performance over just the player's last 15 events — a read on current form rather than the full season.",
  last15_power: "A rolling snapshot of power/driving performance over just the player's last 15 events.",
  last15_accuracy: "A rolling snapshot of driving accuracy over just the player's last 15 events.",
  last15_short_game: "A rolling snapshot of short-game performance over just the player's last 15 events.",
  last15_putting: "A rolling snapshot of putting performance over just the player's last 15 events.",
  club_head_speed: "Average speed of the club head at impact, in miles per hour — the raw power behind the swing.",
  ball_speed: "Average speed of the ball immediately after impact, in miles per hour.",
  smash_factor: "Ball speed divided by club head speed — how efficiently contact is made. The theoretical max with a driver is around 1.5.",
  launch_angle: "The angle, in degrees, the ball leaves the clubface at. Higher launch generally helps carry the ball farther with modern driver technology.",
  spin_rate: "How fast the ball spins right after impact, in rpm. Too much spin costs distance; too little can make the ball hard to control.",
  apex_height: "The peak height the ball reaches in the air on a tee shot, in feet.",
  hang_time: "How many seconds the ball stays in the air on a tee shot.",
  carry_distance: "How far the ball travels through the air before it first touches the ground, not counting roll.",
  total_distance_efficiency: "A ranking of how much of a hole's distance is covered by the tee shot alone — rewards drives that cover a large share of the hole.",
  total_driving_efficiency: "A combined ranking of carry efficiency and other driving-distance measures into one score.",
};

export const EXTENDED_CATEGORY_ORDER = [
  "Scoring",
  "Off the Tee",
  "Approach",
  "Around the Green",
  "Putting",
  "Ratings",
  "Team & Majors",
  "Streaks",
  "Recent Form",
  "Swing Metrics",
];

// Label + category for each extended stat key, used by the glossary page
// to list every category without needing a database round trip. Keep in
// sync with EXTENDED_STATS in scripts/fetch_extended_stats.py.
export const EXTENDED_STAT_CATALOG: { key: string; label: string; category: string }[] = [
  { key: "par3_scoring_avg", label: "Par 3 Scoring Average", category: "Scoring" },
  { key: "par4_scoring_avg", label: "Par 4 Scoring Average", category: "Scoring" },
  { key: "par5_scoring_avg", label: "Par 5 Scoring Average", category: "Scoring" },
  { key: "scoring_avg_actual", label: "Scoring Average (Actual)", category: "Scoring" },
  { key: "scoring_avg_before_cut", label: "Scoring Average Before Cut", category: "Scoring" },
  { key: "final_round_scoring_avg", label: "Final Round Scoring Average", category: "Scoring" },
  { key: "bounce_back", label: "Bounce Back", category: "Scoring" },
  { key: "consecutive_cuts", label: "Consecutive Cuts", category: "Scoring" },
  { key: "rounds_in_60s", label: "Rounds in the 60s", category: "Scoring" },
  { key: "sub_par_rounds", label: "Sub-Par Rounds", category: "Scoring" },
  { key: "lowest_round", label: "Lowest Round", category: "Scoring" },
  { key: "bogey_average", label: "Bogey Average", category: "Scoring" },
  { key: "birdie_to_bogey_ratio", label: "Birdie to Bogey Ratio", category: "Scoring" },
  { key: "total_driving", label: "Total Driving", category: "Off the Tee" },
  { key: "longest_drives", label: "Longest Drives", category: "Off the Tee" },
  { key: "driving_pct_300_plus", label: "Driving Pct. 300+ (All Drives)", category: "Off the Tee" },
  { key: "left_tendency", label: "Left Tendency", category: "Off the Tee" },
  { key: "right_tendency", label: "Right Tendency", category: "Off the Tee" },
  { key: "approach_50_75", label: "Approaches from 50-75 yards", category: "Approach" },
  { key: "approach_75_100", label: "Approaches from 75-100 yards", category: "Approach" },
  { key: "approach_100_125", label: "Approaches from 100-125 yards", category: "Approach" },
  { key: "approach_125_150", label: "Approaches from 125-150 yards", category: "Approach" },
  { key: "approach_150_175", label: "Approaches from 150-175 yards", category: "Approach" },
  { key: "approach_175_200", label: "Approaches from 175-200 yards", category: "Approach" },
  { key: "approach_200_plus", label: "Approaches from > 200 yards", category: "Approach" },
  { key: "proximity_to_hole", label: "Proximity to Hole", category: "Approach" },
  { key: "proximity_arg", label: "Proximity to Hole (Around the Green)", category: "Approach" },
  { key: "proximity_rough", label: "Proximity to Hole from Rough", category: "Approach" },
  { key: "proximity_sand", label: "Proximity to Hole from Sand", category: "Approach" },
  { key: "proximity_fringe", label: "Proximity to Hole from Fringe", category: "Approach" },
  { key: "going_for_the_green", label: "Going for the Green", category: "Approach" },
  { key: "going_for_green_birdie_or_better", label: "Going for the Green - Birdie or Better", category: "Approach" },
  { key: "scrambling_rough", label: "Scrambling from the Rough", category: "Around the Green" },
  { key: "scrambling_sand", label: "Scrambling from the Sand", category: "Around the Green" },
  { key: "scrambling_fringe", label: "Scrambling from the Fringe", category: "Around the Green" },
  { key: "scrambling_other", label: "Scrambling from Other Locations", category: "Around the Green" },
  { key: "one_putt_pct", label: "One-Putt Percentage", category: "Putting" },
  { key: "three_putt_avoidance", label: "3-Putt Avoidance", category: "Putting" },
  { key: "putting_from_3ft", label: "Putting from 3'", category: "Putting" },
  { key: "putting_from_5ft", label: "Putting from 5'", category: "Putting" },
  { key: "putting_inside_5ft", label: "Putting from Inside 5'", category: "Putting" },
  { key: "putting_from_10ft", label: "Putting from 10'", category: "Putting" },
  { key: "putting_from_25plus", label: "Putting from > 25'", category: "Putting" },
  { key: "putts_made_over_10ft_per_event", label: "Putts Made Per Event Over 10'", category: "Putting" },
  { key: "putts_made_over_20ft_per_event", label: "Putts Made Per Event Over 20'", category: "Putting" },
  { key: "power_rating", label: "Power Rating", category: "Ratings" },
  { key: "accuracy_rating", label: "Accuracy Rating", category: "Ratings" },
  { key: "short_game_rating", label: "Short Game Rating", category: "Ratings" },
  { key: "putting_rating", label: "Putting Rating", category: "Ratings" },
  { key: "ball_striking", label: "Ball Striking", category: "Ratings" },
  { key: "scoring_rating", label: "Scoring Rating", category: "Ratings" },
  { key: "ryder_cup_points", label: "Ryder Cup Points", category: "Team & Majors" },
  { key: "presidents_cup_points_us", label: "Presidents Cup Points (United States)", category: "Team & Majors" },
  { key: "presidents_cup_points_intl", label: "Presidents Cup Points (International)", category: "Team & Majors" },
  { key: "consecutive_birdies_streak", label: "Consecutive Birdies Streak", category: "Streaks" },
  { key: "best_60s_streak", label: "Best Rounds in 60's Streak", category: "Streaks" },
  { key: "current_par_or_better_streak", label: "Current Par or Better Streak", category: "Streaks" },
  { key: "last15_scoring", label: "Last 15 Events - Scoring", category: "Recent Form" },
  { key: "last15_power", label: "Last 15 Events - Power", category: "Recent Form" },
  { key: "last15_accuracy", label: "Last 15 Events - Accuracy", category: "Recent Form" },
  { key: "last15_short_game", label: "Last 15 Events - Short Game", category: "Recent Form" },
  { key: "last15_putting", label: "Last 15 Events - Putting", category: "Recent Form" },
  { key: "club_head_speed", label: "Club Head Speed", category: "Swing Metrics" },
  { key: "ball_speed", label: "Ball Speed", category: "Swing Metrics" },
  { key: "smash_factor", label: "Smash Factor", category: "Swing Metrics" },
  { key: "launch_angle", label: "Launch Angle", category: "Swing Metrics" },
  { key: "spin_rate", label: "Spin Rate", category: "Swing Metrics" },
  { key: "apex_height", label: "Apex Height", category: "Swing Metrics" },
  { key: "hang_time", label: "Hang Time", category: "Swing Metrics" },
  { key: "carry_distance", label: "Carry Distance", category: "Swing Metrics" },
  { key: "total_distance_efficiency", label: "Total Distance Efficiency", category: "Swing Metrics" },
  { key: "total_driving_efficiency", label: "Total Driving Efficiency", category: "Swing Metrics" },
];

export const GLOSSARY_INTRO = [
  {
    term: "Strokes Gained",
    body: "The modern standard for measuring skill in golf. Instead of just counting shots, it compares a player's result on every single shot to a massive database of how the average pro performs from that exact same spot. A positive number means they gained strokes on the field (played better than average); negative means they lost strokes. It's the closest thing golf has to an all-in-one performance score.",
  },
  {
    term: "FedExCup",
    body: "The PGA Tour's season-long championship race. Every player earns points based on how they finish in each event, and the standings determine which players advance to the Tour's playoffs and who wins a large postseason bonus.",
  },
  {
    term: "Official World Golf Ranking (OWGR)",
    body: "A ranking of every notable professional golfer on Earth — not just PGA Tour members — based on results over the past two years. It's used to decide who gets into major championships and other elite events.",
  },
  {
    term: "Par, Birdie, Eagle, Bogey",
    body: "Par is the number of strokes an expert golfer is expected to need on a hole. A birdie is one shot better than par, an eagle is two shots better, and a bogey is one shot worse. Lower scores are always better in golf.",
  },
];
